### ISSUE TITLE
Instructions are not clear for Rails 3.0

### ISSUE THREAD

**Issue by pivotal-casebook** [efficiency20/ops_middleware#1]
The Rails instructions look to be 2.x only not 3.0 and the rack instructions are not clear how to make it work properly with Rails 3.x. that just leads to a "uninitialized constant E20" NameError.

**Comment by brynary** [comment]
Does this work for you?

```
Rails.application.middleware.with_options :logger => Rails.logger do |m|
  m.use E20::Ops::Middleware::RevisionMiddleware
  m.use E20::Ops::Middleware::HostnameMiddleware
  m.use E20::Ops::Middleware::TransactionIdMiddleware
end
```

(in config/initializers/ops_middleware.rb)

**Comment by pivotal-casebook** [comment]
Negative. Same error. I also tried <AppName>::Application.config.middleware

ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-darwin10.6.0]
Bundler version 1.0.10
rubygems 1.5.0
passenger 3.0.2

Relevent bit from Gemfile.lock:
    e20_ops_middleware (2.1.0)
      uuidtools (~> 2.1)

**\* Exception NameError in PhusionPassenger::Rack::ApplicationSpawner (uninitialized constant E20) (process 48315, thread #Thread:0x00000100887678):
    from /Users/pivotal/workspace/casebook2/config/initializers/ops_middleware.rb:2:in `block in <top (required)>'
    from /Users/pivotal/.rvm/gems/ruby-1.9.2-p136@casebook2/gems/activesupport-3.0.3/lib/active_support/core_ext/object/with_options.rb:24:in`with_options'
    from /Users/pivotal/workspace/casebook2/config/initializers/ops_middleware.rb:1:in `<top (required)>'
    ...
    from /Users/pivotal/workspace/casebook2/config/environment.rb:5:in`<top (required)>'

I created a brand new rails 3 app just to eliminate all other moving parts and got the same error.

I popped open the gem and created a lib/e20_ops_middleware.rb file with the following contents:

```
require "e20/ops/hostname"
require "e20/ops/middleware"
require "e20/ops/revision"
```

and that seemed to do the trick.

**Comment by brynary** [comment]
Ah hah. Think I figured it out. Here's what we have in our Gemfile:

```
gem "e20_ops_middleware", :require => "e20/ops/middleware"
```

That should resolve it. The middleware.rb file defines autoloads. If this works for you, let me know and I'll update the README

**Comment by pivotal-casebook** [comment]
That did work.

**Comment by brynary** [comment]
Updated readme. Thanks for the bug report!

Also updated it for Rails 3 usage instead of Rails 2.
